version: "3.7"

services:

  php_fpm:
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
      args:
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
        - TIMEZONE=${TIMEZONE}
    restart: always
    container_name: symfony_start_php_fpm
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      APP_ENV: dev
    volumes:
      - type: bind
        source: ./
        target: /var/www/symfony_start
    networks:
      backend:
        ipv4_address: 11.13.10.5
    labels:
      - "traefik.enable=false"

  nginx:
    image: nginx
    restart: always
    container_name: symfony_start_nginx
    depends_on:
      - php_fpm
    volumes:
      - type: bind
        source: ./docker/nginx/default.nginx
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./
        target: /var/www/symfony_start
    networks:
      backend:
        ipv4_address: 11.13.10.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`symfony_start.local`)"
      - "traefik.http.routers.nginx.entrypoints=web"

  # Login:admin Password:password
  portainer:
    image: portainer/portainer:1.22.2
    container_name: symfony_start_portainer
    restart: always
    command: --admin-password '$$2y$$05$$arC5e4UbRPxfR68jaFnAAe1aL7C1U03pqfyQh49/9lB9lqFxLfBqS' -H unix:///var/run/docker.sock
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      backend:
        ipv4_address: 11.13.10.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=web"

  traefik:
    image: traefik:v2.0
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    container_name: symfony_start_traefik
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        ipv4_address: 11.13.10.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.entrypoints=web"

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "11.13.10.0/24"